package com.amplesky.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.amplesky.ICxfService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-24T10:35:55.321+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "cxfService", 
                  wsdlLocation = "http://localhost:8080/hellocxf?wsdl",
                  targetNamespace = "http://impl.amplesky.com/") 
public class CxfService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.amplesky.com/", "cxfService");
    public final static QName CxfServiceImplPort = new QName("http://impl.amplesky.com/", "CxfServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/hellocxf?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/hellocxf?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ICxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public ICxfService getCxfServiceImplPort() {
        return super.getPort(CxfServiceImplPort, ICxfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public ICxfService getCxfServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CxfServiceImplPort, ICxfService.class, features);
    }

}
