package com.amplesky;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-24T10:35:55.287+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://amplesky.com/", name = "ICxfService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICxfService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://amplesky.com/", className = "com.amplesky.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://amplesky.com/", className = "com.amplesky.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
